---
- name: create {{ chain }} service file
  template:
    src: peer.service.j2
    dest: /etc/systemd/system/{{ chain }}-{{ hostvars[inventory_hostname].peer_name | default(peer_name) }}.service
    owner: root
    group: root
    mode: 0600

- name: enable {{ chain }} service
  systemd:
    name: "{{ chain }}-{{ hostvars[inventory_hostname].peer_name | default(peer_name) }}"
    state: restarted
    daemon_reload: yes
    enabled: yes
  changed_when: false
