---
- name: Wait for system ready
  hosts: all
  gather_facts: no
  tasks:
    - name: Wait for nodes to become reachable
      wait_for_connection:

- name: Darwinia peers
  hosts: peers
  become: yes
  vars:
    chain: "darwinia"
    chain_network_id: "darwinia"
    exec_binary: "/mnt/disk1/node/mainnet/darwinia/darwinia"
  tasks:
    - include_role:
        name: ../roles/peer

