---
- name: Wait for system ready
  hosts: all
  gather_facts: no
  tasks:
    - name: Wait for nodes to become reachable
      wait_for_connection:

- name: Kusama validator peers
  hosts: peers
  become: yes
  tasks:
    - include_role:
        name: ../roles/peer

