- name: Wait for system ready
  hosts: all
  gather_facts: no
  tasks:
    - name: Wait for nodes to become reachable
      wait_for_connection:

- name: Edgeware peers
  hosts: peers
  become: yes
  vars:
    chain: "mandala"
    chain_network_id: "mandala"
    exec_binary: "/mnt/disk1/node/testnet/mandala/acala"
  tasks:
    - include_role:
        name: ../roles/peer