---
- name: Wait for system ready
  hosts: all
  gather_facts: no
  tasks:
    - name: Wait for nodes to become reachable
      wait_for_connection:

- name: Rococo peers
  hosts: peers
  become: yes
  vars:
    chain: "rococo"
    chain_network_id: "rococo"
    exec_binary: "/mnt/disk1/workspace/node/testnet/rococo/rococo"
  tasks:
    - include_role:
        name: ../roles/peer

