---
- name: Wait for system ready
  hosts: all
  gather_facts: no
  tasks:
    - name: Wait for nodes to become reachable
      wait_for_connection:

- name: Westend peers
  hosts: peers
  become: yes
  vars:
    chain: "westend"
    chain_network_id: "westend"
    exec_binary: "/mnt/disk1/workspace/node/testnet/westend/westend"
  tasks:
    - include_role:
        name: ../roles/peer

